## YAML Template.
---
server:
  port: 8585

spring:
  application:
    name: notes-store

spring.profiles.active: mysql
#spring.profiles.active: dev
#spring.profiles.active: production

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
  instance:
    preferIpAddress: true

# ---------------------------------------------------------------------------------------------------------------
# logger configuration
# ---------------------------------------------------------------------------------------------------------------

logging:
  level:
    com.umg.dw.api.util: DEBUG
    com.umg.dw.api.controller: DEBUG
    org.springframework.web: INFO
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
